language: cpp
compiler: clang
before_script:
- sudo apt-get update -qq
script:
- pushd ~
- git clone https://github.com/google/googletest.git && cd googletest && mkdir build && cd build && cmake .. && make
- sudo make install
- popd
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
 provider: script
 skip_cleanup: true
 script:
 - curl -v -S -T allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ukhalecky:$BINTRAY_API_KEY "https://api.bintray.com/content/khalecky/otus21_cpp/homework/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
 on:
  branch: hw2-allocator
